-- Reseed questions (safe for dev). In production, remove TRUNCATE and use controlled migrations.
TRUNCATE TABLE questions RESTART IDENTITY CASCADE;

INSERT INTO questions (question, type, options) VALUES
-- Multiple choice (bank)
('Cual es la definicion mas correcta de metagaming (MG)?', 'multiple', '["Usar informacion OOC para actuar IC","Hacer rol agresivo con armas","Usar /do para describir acciones","Hacer un CK con permiso"]'),
('En Genesis, el comando /do se usa principalmente para:', 'multiple', '["Describir el entorno de forma neutral","Describir acciones que el juego no tiene","Pedir un ID durante el rol","Anunciar un CK"]'),
('En un rol agresivo donde deberia intervenir la policia, la norma indica que:', 'multiple', '["Debes usar /entorno describiendo la situacion","Solo usas /entorno si te conviene","No hace falta avisar nunca","Solo el staff puede usar /entorno"]'),
('Cual de estas afirmaciones sobre el rol de entorno (RdE) es correcta?', 'multiple', '["Debe ser neutral y puede perjudicarte","Siempre debe favorecerte si lo roleas bien","Solo existe en zonas vacias","Solo aplica a roles ilegales"]'),
('Segun la normativa, decir insultos racistas u homofobos "por rol" es:', 'multiple', '["Inaceptable y sancionable siempre","Valido si hay motivo IC","Valido si se censura","Valido si lo aprueba el otro jugador"]'),
('Modificar archivos del juego o usar software de cheating/hacking implica:', 'multiple', '["Expulsion de la comunidad","Un simple aviso","Solo se sanciona si te pillan en video","Se permite si es visual"]'),
('Que es lo correcto sobre IC y OOC?', 'multiple', '["No mezclar informacion entre ambos planos","Usar OOC para mejorar el rol IC","Usar IC para justificar insultos OOC","Ignorar las diferencias si hay buen rol"]'),
('Que afirmacion describe mejor el comando /me?', 'multiple', '["Acciones del personaje que el juego no incorpora","Describir el entorno de forma neutral","Pedir ID al final del rol","Rol de camaras del local"]'),
('Valorar tu vida significa principalmente:', 'multiple', '["Evitar decisiones suicidas sin sentido y actuar con autopreservacion","Ganar siempre el rol aunque sea imposible","Ignorar armas apuntandote si quieres ser valiente","Hacer VDM para escapar"]'),
('Sobre el modulador de voz, la norma indica que:', 'multiple', '["Debes abrir ticket y obtener permiso tras pruebas","Se permite sin avisar si suena bien","Solo esta prohibido para SAPD","Solo esta permitido si te lo compra el staff"]'),
('Sobre reportes, el plazo maximo para reportar un rol es:', 'multiple', '["5 dias","24 horas","48 horas","15 dias"]'),
('Sobre apelaciones de sanciones (3 o mas dias), si no apelas en:', 'multiple', '["24 horas pierdes la oportunidad","5 dias pierdes la oportunidad","1 hora pierdes la oportunidad","Siempre puedes apelar sin limite"]'),
('Rol de camaras: que es lo correcto?', 'multiple', '["No se puede rolear con /me y /do, debes aportar grabacion","Se puede rolear si escribes un /do convincente","Se puede rolear si hay testigos IC","Se puede rolear si lo haces rapido"]'),
('Rol familiar entre personajes (hermano/padre/hijo) en Genesis es:', 'multiple', '["No valido","Valido si hay buena historia","Valido solo con permiso del staff","Valido si ambos jugadores lo aceptan"]'),
('Mal uso de /pedirID: se considera abuso si se usa:', 'multiple', '["Antes o durante el rol (debe ser al finalizar)","Al finalizar el rol","En un ticket de soporte","En un roleo tranquilo"]'),
('Que esta prohibido sobre fotos IC y IA?', 'multiple', '["Subir fotos IRL o retocadas con IA como si fueran IC","Usar capturas del juego sin editar","Usar imagenes no realistas que mantengan estetica GTA V","Usar imagenes sin marcas registradas"]'),
('Que esta prohibido siempre sobre copyright?', 'multiple', '["Subir fotografias con marcas registradas","Subir capturas del juego","Subir imagenes con estetica GTA","Subir memes sin logos"]'),
('Segun politicas, compartir informacion personal de otro jugador (PII) es:', 'multiple', '["Prohibido","Permitido si es por rol","Permitido si es en privado","Permitido si el otro lo hizo primero"]'),
('Segun politicas, personajes menores de edad:', 'multiple', '["No estan permitidos","Se permiten con consentimiento","Se permiten solo para civil","Se permiten si no hay rol sensible"]'),
('Sobre contenido extremadamente violento real (mundo real), la norma dice:', 'multiple', '["No se permite compartir representaciones graficas reales","Se permite si esta censurado","Se permite si es por rol","Se permite si es solo una imagen"]'),
('Vacatio legis / vacios legales significa que:', 'multiple', '["El staff puede sentar criterio cuando no haya norma explicita","Puedes hacer lo que quieras si no esta escrito","Solo aplica a SAPD","Solo aplica en zonas safe"]'),
('Cuando se trata de un personaje con trastorno psiquiatrico, la norma recalca que:', 'multiple', '["Debe tener buena historia y atenerse a consecuencias IC (posible CK)","Puede hacer cualquier cosa sin consecuencias","No puede existir nunca","Solo puede ser civil"]'),
('Que afirmacion es correcta sobre nombres de personaje?', 'multiple', '["No usar nombres de figuras publicas o historicas ni nombres troll","Puedes usar cualquier nombre si es gracioso","Puedes usar el nombre de un politico si cambias una letra","Puedes usar el nombre de un actor si no es famoso"]'),
('Sobre odio/discriminacion basados en identidad:', 'multiple', '["Esta prohibido atacar por caracteristicas protegidas","Esta permitido si es humor IC","Esta permitido si nadie se queja","Solo es sancionable en OOC"]'),

-- Open questions (bank)
('Explica con un ejemplo complejo como evitar mezclar IC y OOC cuando tienes informacion fuera del juego que te beneficia.', 'open', NULL),
('Redacta un /entorno neutral (sin favorecerte) para una situacion de tiros en via publica con heridos. Explica por que es neutral.', 'open', NULL),
('Redacta un /entorno neutral para una situacion no agresiva pero donde cualquier ciudadano avisaria a autoridades (ej: comportamiento sospechoso).', 'open', NULL),
('Explica la diferencia entre /me y /do con dos ejemplos realistas y justifica por que uno seria invalido si lo cambiases.', 'open', NULL),
('Describe una situacion donde el rol de entorno te perjudica aunque tu intencion fuese beneficiarte. Que deberias hacer para respetarlo?', 'open', NULL),
('Explica que significa "valorar tu vida" en un escenario donde te apuntan con un arma y estas solo. Incluye decisiones concretas.', 'open', NULL),
('Plantea un rol donde el fairplay implique perder una ventaja IC. Que haras para que el rol sea entretenido para todos?', 'open', NULL),
('Describe un ejemplo de powergaming liberado valido y otro invalido. En ambos casos indica donde esta el limite.', 'open', NULL),
('Que haras si detectas un bug importante que podria dar ventajas? Indica el proceso correcto y por que.', 'open', NULL),
('Explica por que "no saber la normativa" no exime de sancion. Pon un ejemplo de como se aplicaria.', 'open', NULL),
('Describe un caso donde el staff deberia intervenir aunque no exista una norma explicita. Que principio aplicaria?', 'open', NULL),
('Explica por que el uso de insultos graves contra identidades protegidas no es aceptable ni siquiera "por rol".', 'open', NULL),
('Explica que es un espacio seguro en una comunidad RP y como contribuyes a ello en situaciones de conflicto.', 'open', NULL),
('Diferencia IC vs OOC con un caso complejo: un clip externo te da informacion sobre un conflicto. Como actuas correctamente?', 'open', NULL),
('Describe un ejemplo de metagaming involuntario y como lo corregirias en el momento sin romper el rol.', 'open', NULL),
('Explica por que el rol de camaras no se acepta con /me y /do. Que pruebas se exigen y por que?', 'open', NULL),
('Que implica el mal uso de /pedirID y por que debe hacerse al finalizar el rol? Pon un ejemplo.', 'open', NULL),
('Por que no se permite rolear familia directa entre personajes? Explica el problema con CK y conocimiento heredado.', 'open', NULL),
('Define interpretacion de personaje (IdP) y explica como se relaciona con tu ficha. Que pasa si cambias de objetivos sin justificarlos?', 'open', NULL),
('Si quieres usar modulador de voz, que pasos concretos debes seguir segun la norma? Por que se pide ese control?', 'open', NULL),
('Explica una situacion donde compartir una imagen IC hecha con IA romperia la estetica. Da un ejemplo de algo permitido y algo prohibido.', 'open', NULL),
('Que consecuencias y riesgos tiene modificar archivos del juego aunque sea "solo visual"? Explica desde el punto de vista de fairplay.', 'open', NULL),
('Explica que es VDM/DM/RK/PK/CK en tus palabras y aporta un ejemplo de cada uno. (Si no conoces un termino, di como lo resolverias con staff.)', 'open', NULL),
('Plantea un escenario donde se incumplen 3 normas a la vez (ej: MG + insultos + rde). Identificalas y explica como evitarlo.', 'open', NULL),
('Que haras si otro jugador intenta forzarte un rol injusto o ilogico? Explica como lo gestionas sin irte a OOC toxico.', 'open', NULL),
('Redacta un /do correcto (neutral) para describir el estado de una escena tras un accidente de trafico. Explica por que no es sesgado.', 'open', NULL),
('Que significa que el staff puede "sentar criterio" (vacatio legis)? Da un ejemplo realista en RP.', 'open', NULL),
('Explica la norma de reportes (plazo) y por que existe. Que haces si se te pasa el plazo?', 'open', NULL),
('Explica el procedimiento y limite de apelacion de sanciones: cuando aplica y cuando se pierde la oportunidad.', 'open', NULL),
('Describe un caso de abuso de rol sensible. Explica que lo hace sensible y como actuar correctamente.', 'open', NULL),
('Sobre politicas: explica por que esta prohibido compartir PII (datos personales) incluso si crees que es "merecido".', 'open', NULL),
('Sobre seguridad de menores: explica por que esta prohibido que los personajes sean menores y que implicaciones tiene cualquier insinuacion.', 'open', NULL),
('Rol de suicidio: explica cuando podria ser un cierre narrativo valido y cuando se consideraria promocion peligrosa.', 'open', NULL),
('Extremismo violento en RP: explica por que no se permite glorificar organizaciones reales y como evitar referencias indebidas.', 'open', NULL),
('Explica por que un rol "libre de restricciones" aun necesita limites y normas para proteger a la comunidad.', 'open', NULL),
('Da un ejemplo de como el RdE te obliga a actuar de cierta forma segun el lugar (zona concurrida vs aislada).', 'open', NULL),
('Plantea una situacion donde el uso de /do podria ser abuso si lo usas a tu favor. Reescribelo de forma neutral.', 'open', NULL),
('Plantea una situacion donde el uso de /me seria incorrecto por imponer resultados. Explica como hacerlo bien.', 'open', NULL),
('Explica por que no se admiten nombres de figuras publicas, politicos o historicos. Incluye un problema concreto que generaria.', 'open', NULL),
('Si roleas un personaje con trastorno psiquiatrico: que limites narrativos y de coherencia debes respetar para no usarlo como excusa?', 'open', NULL),
('Explica que significa que Genesis busca roles "complejos, rizomaticos y entretenidos". Como lo aplicas en tu PJ?', 'open', NULL),
('Describe una situacion donde el staff sancionaria como cauce correcto en vez de solo ensenar la norma. Por que?', 'open', NULL),
('En un conflicto IC, como evitas que se convierta en conflicto OOC? Da un protocolo personal de 4 pasos.', 'open', NULL),
('Plantea un ejemplo de spam/estafa (politicas) dentro de la comunidad y explica por que se considera perjudicial.', 'open', NULL),
('Explica por que el acoso/acecho/amenazas OOC o IC a la identidad de un jugador no tienen cabida en la comunidad.', 'open', NULL),
('Explica como harias una sugerencia o critica en la comunidad sin faltar al respeto. Da un ejemplo de mensaje.', 'open', NULL),
('Describe un rol donde deberias usar /entorno aunque no haya agresion directa. Justifica por que lo usarias.', 'open', NULL),
('Explica como evitarias "powergaming" al describir una pelea: que tipo de frases evitarias en /me y por que.', 'open', NULL),
('Imagina que alguien comparte una captura IRL como si fuera IC: que norma rompe y que consecuencias puede tener para el servidor?', 'open', NULL),
('Explica por que las marcas registradas (copyright) estan prohibidas en imagenes subidas al servidor. Incluye un riesgo real.', 'open', NULL),
('Describe una situacion donde alguien intenta usar un vacio legal ("no esta escrito") para justificar un rol toxico. Como responde el staff?', 'open', NULL),
('Define "respeto y cordialidad" en un RP agresivo: como mantienes limites sin romper la tension narrativa?', 'open', NULL),
('Redacta un ejemplo de /entorno MAL hecho (sesgado) y luego reescribelo bien. Explica la diferencia.', 'open', NULL),
('Si un usuario no respeta el RdE en zona concurrida, que consecuencias logicas IC podrian ocurrir? Explica al menos 3.', 'open', NULL),
('Explica un caso donde el fairplay significa aceptar una consecuencia grave para tu PJ (perdida, CK, etc) y aun asi jugarlo.', 'open', NULL),
('Plantea un rol donde tu PJ quiere algo dificil (objetivo) y explica como lo desarrollarias sin hacer atajos OOC.', 'open', NULL),
('Explica por que la comunidad protege a todos los miembros independientemente de genero, orientacion sexual o edad. Como se aplica en sanciones?', 'open', NULL),
('En tu opinion, por que el uso de palabras hirientes puede destruir un rol incluso si la historia es buena? Explica con un caso.', 'open', NULL),
('Que haras si dudas sobre una norma durante un rol? Explica como actuar sin parar la escena y como usar el soporte luego.', 'open', NULL),
('Explica como funciona el concepto de "espacio seguro" cuando hay humor negro o provocaciones IC. Donde esta el limite?', 'open', NULL),
('Plantea un escenario donde la policia deberia aparecer por RdE. Redacta el /entorno y explica el motivo.', 'open', NULL),
('Explica por que "entorpecer el juego de los demas" se trata como expulsion directa en el caso de cheating/hacking.', 'open', NULL),
('Da un ejemplo de como un PJ evoluciona con el tiempo sin traicionar sus axiomas iniciales. Explica que se puede cambiar y que no.', 'open', NULL),
('Explica un caso donde un personaje psiquiatrico podria acabar en CK por sus actos IC. Que lo haria coherente y no una excusa?', 'open', NULL),
('Que harias si ves a otro jugador usando insultos prohibidos? Explica la respuesta correcta y como reportarias (si procede).', 'open', NULL),
('Redacta un /do que describa un entorno hostil (clima, ruido, gente) sin favorecerte ni perjudicar al otro de forma artificial.', 'open', NULL),
('Explica por que un servidor "plural y libre" aun puede expulsar indefinidamente por ataques a identidades. Justifica con principios.', 'open', NULL),
('Explica un caso de intimidacion/acecho y por que esta dentro de lo prohibido segun politicas.', 'open', NULL),
('Explica que significa "discutir o permitir compra/venta real de armas o drogas" y por que es una linea roja.', 'open', NULL),
('Plantea un caso donde se roza la estafa/spam con mensajes repetidos. Que haria el staff y que deberias hacer tu?', 'open', NULL),
('Explica por que las imagenes realistas IA pueden romper el contexto de GTA V. Da un criterio practico para distinguirlo.', 'open', NULL),
('Plantea un caso donde una imagen IA podria ser aceptable. Explica que limites debe cumplir (sin sexual, estetica, etc).', 'open', NULL),
('Describe una situacion donde un jugador intenta justificar discriminacion por "su personaje". Como lo detiene la norma?', 'open', NULL),
('Explica como mantendrias la cordialidad si pierdes un rol importante. Que haras inmediatamente despues para evitar OOC.', 'open', NULL),
('Redacta una respuesta corta (2-3 frases) que darias si alguien intenta provocar OOC en mitad de un rol.', 'open', NULL),
('Explica por que el staff puede ensenar pero tambien sancionar segun circunstancias. Da un ejemplo de cada enfoque.', 'open', NULL),
('Explica por que el comando /do debe ser neutral y como detectarias que tu propio /do esta sesgado a tu favor.', 'open', NULL),
('Plantea un rol agresivo y explica cuando EXACTAMENTE lanzas /entorno y que informacion minima incluyes.', 'open', NULL),
('Que implica "juego limpio" en un servidor RP? Explica con ejemplos de conducta y de trampas tecnicas.', 'open', NULL),
('Describe un caso donde un usuario comparte informacion personal (telefono, direccion, redes) de otro jugador. Que pasa y por que?', 'open', NULL),
('Explica que medidas tomarias para evitar que tu PJ sea troll (nombre, acciones, coherencia).', 'open', NULL),
('Plantea un caso donde tu PJ quiere cometer un delito en zona con mucha gente. Explica el RdE y las consecuencias probables.', 'open', NULL),
('Explica la diferencia entre insultar al PJ dentro de limites y atacar identidades protegidas. Donde esta la linea roja?', 'open', NULL),
('Describe una situacion donde el staff cierra un ticket de oficio por no apelar a tiempo. Que aprendizaje sacas?', 'open', NULL),
('Explica por que Genesis no esta afiliado a Rockstar/FiveM y como eso se relaciona con cumplimiento de politicas.', 'open', NULL),
('Plantea un escenario donde tu conducta podria interpretarse como acoso. Explica como lo evitarias y que senales vigilas.', 'open', NULL),
('Si alguien amenaza OOC a otro jugador por un rol, que haces? Describe pasos concretos.', 'open', NULL),
('Define "amenaza" e "intimidacion" en el marco de politicas. Da un ejemplo claro de cada una.', 'open', NULL),
('Explica como gestionas tu propia frustracion cuando algo te sale mal IC sin descargarlo contra otros.', 'open', NULL),
('Plantea una situacion donde el rol seria invalido por falta de logica. Explica que parte falla y como se arregla.', 'open', NULL),
('Explica por que el staff no acepta "no habia norma" como defensa. Relaciona con vacatio legis.', 'open', NULL),
('Redacta un /entorno para un robo silencioso en una tienda vacia. Justifica si aplica o no segun la logica y RdE.', 'open', NULL),
('Explica por que la comunidad no permite "programas de hacking" aunque sean fuera del juego. Relaciona con juego limpio.', 'open', NULL),
('Plantea un caso donde una sancion deberia apelarse y otro donde no tiene sentido apelar. Explica por que.', 'open', NULL),
('Explica como te aseguras de que tu Steam perfil es publico y por que se requiere para whitelist.', 'open', NULL),
('Plantea un caso donde un jugador intenta usar capturas externas como pruebas IC sin grabacion. Que problema hay?', 'open', NULL),
('Explica por que en roles agresivos es obligatorio describir entorno y como eso mejora la experiencia para ambos lados.', 'open', NULL),
('Redacta un ejemplo de /me adecuado para registrar una accion fisica sin imponer reaccion del otro. Explica el limite.', 'open', NULL),
('Plantea un caso donde la administracion debe proteger a un jugador vulnerable aunque el rol fuese "intenso". Como lo haria?', 'open', NULL),
('Explica que significa "plural y diverso" en una comunidad RP y como evitar conductas discriminatorias sutiles.', 'open', NULL),
('Plantea un caso donde se discute compra/venta real de objetos ilegales. Explica por que esta prohibido incluso como "broma".', 'open', NULL),
('Define "extremismo violento" segun politicas y explica por que se evita en un servidor RP.', 'open', NULL),
('Explica por que el servidor no permite "contenido sangriento real" y como diferenciarlo de violencia ficticia de GTA.', 'open', NULL),
('Plantea un rol donde se haria referencia a autolesion. Explica como evitar promocion y mantener responsabilidad.', 'open', NULL),
('Explica por que la comunidad recomienda abrir ticket ante dudas. Como lo harias sin interrumpir el rol en curso?', 'open', NULL);

